- regExp: "library\/sirens\/"
  labels: ["library"]
- regExp: "library\/auto\/"
  labels: ["library"]
- regExp: "library\/default\/"
  labels: ["library"]
- regExp: "library\/vehicles\/"
  labels: ["library"]
- regExp: "\\.github/builder"
  labels: ["ci/cd"]
- regExp: "\\.github/workflows"
  labels: ["ci/cd"]